export const FUN_PREFIXES = [
    'Cooking up',
    'Summoning',
    'Brewing',
    'Compiling',
    'Gathering',
    'Assembling',
    'Forging',
    'Synthesizing',
    'Unearthing',
    'Decoding',
    'Wrangling',
    'Harvesting',
    'Constructing',
    'Generating',
    'Calculating',
    'Deriving',
    'Extracting',
    'Fetching',
    'Retrieving',
    'Loading',
    'Concocting',
    'Fabricating',
    'Unlocking',
    'Discovering',
    'Mining',
    'Weaving',
    'Knitting',
    'Sculpting',
    'Polishing',
    'Refining',
    'Distilling',
    'Transmuting',
    'Conjuring',
    'Manifesting',
    'Materializing',
    'Hatching',
    'Orchestrating',
    'Engineering',
    'Architecting',
    'Spinning',
];

export const getRandomPrefix = () => {
    return FUN_PREFIXES[Math.floor(Math.random() * FUN_PREFIXES.length)];
};
