import stringify from 'fast-stable-stringify';
import * as fs from 'fs';
import * as path from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import type { Entitlements } from '../src/entitlements';

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Parses a LookML entitlements block and converts it to JSON
 */
function parseEntitlements(lookmlContent: string): Partial<Entitlements> {
    // Find the entitlements block - match from entitlements: { to the closing }
    const entitlementsMatch = lookmlContent.match(
        /entitlements:\s*\{([\s\S]*?)\n\s*\}/
    );

    if (!entitlementsMatch) {
        throw new Error('Could not find entitlements block in manifest.lkml');
    }

    const entitlementsBlock = entitlementsMatch[1];
    const result: Partial<Entitlements> = {};

    // Split by lines and process each one
    const lines = entitlementsBlock.split('\n');

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i].trim();

        // Skip empty lines
        if (!line) continue;

        // Check if this is an array start (e.g., "core_api_methods: [" or "core_api_methods: [")
        const arrayMatch = line.match(/^(\w+):\s*\[/);
        if (arrayMatch) {
            const key = arrayMatch[1];
            const arrayItems: string[] = [];

            // Collect array items until we find the closing bracket
            i++; // Move to next line
            while (i < lines.length) {
                line = lines[i].trim();

                // Check for closing bracket (might be on same line or its own line)
                if (line === ']' || line.endsWith(']')) {
                    // If there's content before the closing bracket, extract it
                    if (line !== ']') {
                        const beforeBracket = line.replace(/\]$/, '').trim();
                        if (beforeBracket) {
                            // Remove trailing comma and quotes if present
                            const cleanItem = beforeBracket
                                .replace(/,$/, '')
                                .trim();
                            const itemMatch = cleanItem.match(
                                /^"([^"]+)"|^([^",\s]+)/
                            );
                            if (itemMatch) {
                                arrayItems.push(itemMatch[1] || itemMatch[2]);
                            }
                        }
                    }
                    break;
                }

                // Remove trailing comma if present
                const cleanLine = line.replace(/,$/, '').trim();

                // Extract quoted string or unquoted value
                const itemMatch = cleanLine.match(/^"([^"]+)"|^([^",\s]+)/);
                if (itemMatch) {
                    arrayItems.push(itemMatch[1] || itemMatch[2]);
                }

                i++;
            }

            result[key] = arrayItems;
            continue;
        }

        // Check for boolean values (e.g., "local_storage: yes")
        const boolMatch = line.match(/^(\w+):\s*(yes|no)$/);
        if (boolMatch) {
            const key = boolMatch[1];
            const value = boolMatch[2] === 'yes';
            result[key] = value;
            continue;
        }

        // Check for string values (e.g., "key: value")
        const stringMatch = line.match(/^(\w+):\s*(.+)$/);
        if (stringMatch) {
            const key = stringMatch[1];
            let value = stringMatch[2].trim();

            // Remove quotes if present
            if (
                (value.startsWith('"') && value.endsWith('"')) ||
                (value.startsWith("'") && value.endsWith("'"))
            ) {
                value = value.slice(1, -1);
            }

            result[key] = value;
        }
    }

    return result;
}

/**
 * Generates TypeScript file content from entitlements object
 */
function generateTSContent(entitlements: Partial<Entitlements>): string {
    const lines: string[] = [];
    lines.push('// This file is automatically generated from manifest.lkml');
    lines.push('// Do not edit this file directly');
    lines.push(`

declare global {
    interface Window {
        lookerExtensionMetadata: {
            entitlements: Entitlements;
            label: string;
        };
    }
}

type TBooleanOrNull = boolean | null;

export interface Entitlements {
    local_storage: boolean;
    navigation: boolean;
    new_window: boolean;
    new_window_external_urls: string[];
    raw_api_request: TBooleanOrNull;
    allow_forms: TBooleanOrNull;
    allow_same_origin: TBooleanOrNull;
    use_form_submit: TBooleanOrNull;
    use_embeds: TBooleanOrNull;
    use_downloads: TBooleanOrNull;
    use_iframes: TBooleanOrNull;
    use_clipboard: TBooleanOrNull;
    use_tracking_api: TBooleanOrNull;
    core_api_methods: string[];
    external_api_urls: string[];
    oauth2_urls: string[];
    global_user_attributes: string[];
    scoped_user_attributes: string[];
}
`);
    lines.push(
        `export const required_entitlements: Partial<Entitlements> = ${stringify(
            entitlements
        )};`
    );
    return lines.join('\n');
}

/**
 * Main function to generate entitlements.ts from manifest.lkml
 */
function generateEntitlements(): void {
    const manifestPath = path.join(__dirname, '..', 'manifest.lkml');
    const outputPath = path.join(__dirname, '..', 'src', 'entitlements.ts');

    try {
        // Read manifest.lkml
        const manifestContent = fs.readFileSync(manifestPath, 'utf8');

        // Parse entitlements
        const entitlements = parseEntitlements(manifestContent);

        // Generate TypeScript content
        const tsContent = generateTSContent(entitlements);

        // Write to entitlements.ts
        fs.writeFileSync(outputPath, tsContent, 'utf8');

        console.log(
            '✓ Successfully generated entitlements.ts from manifest.lkml'
        );
    } catch (error) {
        const errorMessage =
            error instanceof Error ? error.message : String(error);
        console.error('✗ Error generating entitlements.ts:', errorMessage);
        process.exit(1);
    }
}

generateEntitlements();
