// This file is automatically generated from manifest.lkml
// Do not edit this file directly


declare global {
    interface Window {
        lookerExtensionMetadata: {
            entitlements: Entitlements;
            label: string;
        };
    }
}

type TBooleanOrNull = boolean | null;

export interface Entitlements {
    local_storage: boolean;
    navigation: boolean;
    new_window: boolean;
    new_window_external_urls: string[];
    raw_api_request: TBooleanOrNull;
    allow_forms: TBooleanOrNull;
    allow_same_origin: TBooleanOrNull;
    use_form_submit: TBooleanOrNull;
    use_embeds: TBooleanOrNull;
    use_downloads: TBooleanOrNull;
    use_iframes: TBooleanOrNull;
    use_clipboard: TBooleanOrNull;
    use_tracking_api: TBooleanOrNull;
    core_api_methods: string[];
    external_api_urls: string[];
    oauth2_urls: string[];
    global_user_attributes: string[];
    scoped_user_attributes: string[];
}

export const required_entitlements: Partial<Entitlements> = {"core_api_methods":["me","session","all_lookml_models","query","lookml_model_explore","run_query","create_sql_query","run_sql_query","query_for_slug","search_dashboards","create_dashboard_element","connection","dashboard","all_connections","artifact","update_artifacts","session"],"external_api_urls":["https://www.lkr.dev/apps/explore-blending/api"],"local_storage":true,"navigation":true,"new_window":true,"use_clipboard":true,"use_embeds":true,"use_form_submit":true};